MWKVVGISQVA*
MVNSVSPRDNRESNYWTRN*
MCCGRDS*
MWCSNCPARAWATP*
Impossivel traduzir
MAGVHEYDGI*
Impossivel traduzir
Impossivel traduzir
MAPPRPPRPGSCRPGAG*
MPACSCSAA*
MCRA*
Impossivel traduzir
MWTGTRTRPPSPATVSSWPDSCT*
MPGVRRKVKPAPKRSENWWWRR*
MQHPTTGPKAN*
MPSAPLLPSRDTATGRP*
MAGRKNSLDVPIR*
M*
M*
MSVV*
Impossivel traduzir
MSRTAGCWAAWG*
MPVASNDTEEGRRQNRRVEFRVIQIQ*
MASKIRLAACNVPA*
MVSGNAGLLAAACLSAFLGRFLVAGC*
