MVLKRSRSRKHRAKK*
Impossivel traduzir
Impossivel traduzir
MPP*
METGIEKTGGAAVWTVLRGLWEA*
MAVAKASKNS*
Impossivel traduzir
MVCS*
Impossivel traduzir
MDVPASYRIFF*
MSGPYTA*
MREEQSRRPSSPPQP*
MLHARRQGRRHGCC*
