MAPNCAPWTGRSASTSS*
MPSSDSPRPDSSRDW*
MLPG*
MATPSSPFSAVRIS*
Impossivel traduzir
Impossivel traduzir
Impossivel traduzir
MPAPRPPLPDCARASIGRTSRWR*
MREYGNRAWRFPPRPS*
MFCRC*
Impossivel traduzir
Impossivel traduzir
MPYSSARR*
M*
MPAARQCAAIVST*
MPS*
MPVNACSAVWTSSPTPSK*
MDWKTS*
Impossivel traduzir
MAAQPCLRPA*
MSTSGYPTHRAEVPDG*
MEPLSSSGCRKRWSRVTRRSLWLRNR*
Impossivel traduzir
