MTLFIGR*
Impossivel traduzir
MSVTPWRVR*
Impossivel traduzir
MRGA*
MRASASRSRVLS*
MGTLWRSDS*
MGRLAAAEFCLHFSGNRYSTRISAKAHRG*
MGNHQPGDDAALAGLP*
MQAGCGARSSRPALA*
MRLQAFFLRRRPHIGHRAHLG*
Impossivel traduzir
MASKGRCPAARRRG*
MFERGEPFQGDPSRSPRPKI*
MSWRALKCISWSNTS*
MRRRR*
MQKDCPLRQRRRRGGVVQAFFLYLCGKFQR*
Impossivel traduzir
MQQCASWRCTGAATILHR*
MPPQQIERVQPDEQP*
MWRRFASRRV*
MAR*
Impossivel traduzir
MH*
MR*
MTRRSQSQVAAA*
MLWPTP*
MPSCTLWTNSL*
MWWKATCW*
MEERASPLKSEETRGRVL*
MIAPGRPSRLGILPSSLRDAPL*
MATRSPSGEKYGSSSQL*
MLAQVH*
Impossivel traduzir
