MELLGLSAK*
MSAHSTYTSARRTAGGR*
MWRIFLT*
Impossivel traduzir
Impossivel traduzir
MREYGNRAWRFPPRPS*
Impossivel traduzir
MHRRP*
MSCAWASAAS*
MVASRNQGWP*
Impossivel traduzir
MAPSNSNSS*
MGIPLLCTPGAGQQCKLQPET*
MPAPQAADTAARARAFRRDPSNTSQKI*
MHASESEDGCLHPRD*
MCSPSP*
MVRSRLGRTYPLWIDGKDVETPDTIATATRPDRTR*
MACKVPWEASAW*
