Robo saiu do tabuleiro apos 4 passo(s)
Robo entrou em loop apos 9 passos (loop de tamanho 8)
Robo saiu do tabuleiro apos 8 passo(s)
Robo entrou em loop apos 2 passos (loop de tamanho 2)
Robo saiu do tabuleiro apos 7 passo(s)
Robo entrou em loop apos 11 passos (loop de tamanho 8)
Robo saiu do tabuleiro apos 1 passo(s)
Robo entrou em loop apos 2 passos (loop de tamanho 2)
