Robo entrou em loop apos 9 passos (loop de tamanho 2)
Robo saiu do tabuleiro apos 4 passo(s)
Robo saiu do tabuleiro apos 4 passo(s)
Robo saiu do tabuleiro apos 1 passo(s)
Robo entrou em loop apos 3 passos (loop de tamanho 2)
Robo entrou em loop apos 7 passos (loop de tamanho 2)
Robo entrou em loop apos 2 passos (loop de tamanho 2)
Robo entrou em loop apos 3 passos (loop de tamanho 2)
Robo entrou em loop apos 3 passos (loop de tamanho 2)
Robo entrou em loop apos 8 passos (loop de tamanho 2)
Robo entrou em loop apos 3 passos (loop de tamanho 2)
Robo entrou em loop apos 5 passos (loop de tamanho 2)
