cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 1, coluna 1
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 1, coluna 9
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 1, coluna 11
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 1, coluna 16
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 1, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 2, coluna 2
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 2, coluna 6
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 2, coluna 8
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 2, coluna 12
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 2, coluna 17
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 2, coluna 21
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 3, coluna 3
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 3, coluna 9
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 3, coluna 13
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 3, coluna 17
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 3, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 4, coluna 5
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 4, coluna 8
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 4, coluna 12
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 4, coluna 14
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 4, coluna 16
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 4, coluna 19
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 5, coluna 1
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 5, coluna 5
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 5, coluna 6
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 5, coluna 11
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 5, coluna 21
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 5, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 6, coluna 3
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 6, coluna 5
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 6, coluna 10
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 6, coluna 13
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 6, coluna 15
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 6, coluna 23
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 7, coluna 4
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 7, coluna 11
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 7, coluna 13
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 7, coluna 18
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 7, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 8, coluna 2
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 8, coluna 11
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 8, coluna 14
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 8, coluna 18
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 8, coluna 20
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 8, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 9, coluna 1
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 9, coluna 6
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 9, coluna 9
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 9, coluna 17
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 9, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 3
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 5
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 8
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 12
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 14
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 18
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 19
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 10, coluna 23
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 11, coluna 1
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 11, coluna 2
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 11, coluna 12
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 11, coluna 16
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 11, coluna 20
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 11, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 12, coluna 2
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 12, coluna 4
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 12, coluna 13
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 12, coluna 15
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 12, coluna 17
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 13, coluna 2
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 13, coluna 4
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 13, coluna 7
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 13, coluna 8
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 13, coluna 16
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 13, coluna 20
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 13, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 14, coluna 7
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 14, coluna 17
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 14, coluna 19
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 14, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 15, coluna 3
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 15, coluna 5
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 15, coluna 9
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 15, coluna 12
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 15, coluna 18
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 15, coluna 22
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 16, coluna 4
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 16, coluna 7
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 16, coluna 10
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 16, coluna 18
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 16, coluna 19
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 16, coluna 21
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 17, coluna 4
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 17, coluna 9
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 17, coluna 13
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 17, coluna 17
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 17, coluna 23
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 18, coluna 1
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 18, coluna 6
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 18, coluna 10
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 18, coluna 14
cgatcgatctagctcatcgatatcgccatccgatgcatacctggatacac: linha 18, coluna 19
------ FIM ------

