aaaaaaaaaaaaaaaaaaaaaaaa: linha 1, coluna 8
aaaaaaaaaaaaaaaaaaaaaaaa: linha 1, coluna 17
aaaaaaaaaaaaaaaaaaaaaaaa: linha 2, coluna 1
aaaaaaaaaaaaaaaaaaaaaaaa: linha 2, coluna 5
aaaaaaaaaaaaaaaaaaaaaaaa: linha 2, coluna 6
aaaaaaaaaaaaaaaaaaaaaaaa: linha 2, coluna 7
aaaaaaaaaaaaaaaaaaaaaaaa: linha 2, coluna 16
aaaaaaaaaaaaaaaaaaaaaaaa: linha 3, coluna 1
aaaaaaaaaaaaaaaaaaaaaaaa: linha 3, coluna 7
aaaaaaaaaaaaaaaaaaaaaaaa: linha 3, coluna 12
aaaaaaaaaaaaaaaaaaaaaaaa: linha 3, coluna 14
aaaaaaaaaaaaaaaaaaaaaaaa: linha 4, coluna 1
aaaaaaaaaaaaaaaaaaaaaaaa: linha 4, coluna 5
aaaaaaaaaaaaaaaaaaaaaaaa: linha 4, coluna 8
aaaaaaaaaaaaaaaaaaaaaaaa: linha 4, coluna 13
aaaaaaaaaaaaaaaaaaaaaaaa: linha 5, coluna 2
aaaaaaaaaaaaaaaaaaaaaaaa: linha 5, coluna 6
aaaaaaaaaaaaaaaaaaaaaaaa: linha 5, coluna 7
aaaaaaaaaaaaaaaaaaaaaaaa: linha 6, coluna 9
aaaaaaaaaaaaaaaaaaaaaaaa: linha 6, coluna 12
aaaaaaaaaaaaaaaaaaaaaaaa: linha 7, coluna 8
aaaaaaaaaaaaaaaaaaaaaaaa: linha 7, coluna 10
aaaaaaaaaaaaaaaaaaaaaaaa: linha 7, coluna 12
aaaaaaaaaaaaaaaaaaaaaaaa: linha 8, coluna 9
aaaaaaaaaaaaaaaaaaaaaaaa: linha 8, coluna 14
aaaaaaaaaaaaaaaaaaaaaaaa: linha 9, coluna 7
aaaaaaaaaaaaaaaaaaaaaaaa: linha 9, coluna 15
aaaaaaaaaaaaaaaaaaaaaaaa: linha 10, coluna 6
aaaaaaaaaaaaaaaaaaaaaaaa: linha 10, coluna 7
aaaaaaaaaaaaaaaaaaaaaaaa: linha 10, coluna 9
aaaaaaaaaaaaaaaaaaaaaaaa: linha 10, coluna 12
aaaaaaaaaaaaaaaaaaaaaaaa: linha 10, coluna 17
aaaaaaaaaaaaaaaaaaaaaaaa: linha 11, coluna 8
aaaaaaaaaaaaaaaaaaaaaaaa: linha 11, coluna 12
aaaaaaaaaaaaaaaaaaaaaaaa: linha 11, coluna 18
aaaaaaaaaaaaaaaaaaaaaaaa: linha 12, coluna 11
tttttttttttttttttttttttt: linha 1, coluna 1
tttttttttttttttttttttttt: linha 1, coluna 4
tttttttttttttttttttttttt: linha 1, coluna 9
tttttttttttttttttttttttt: linha 1, coluna 18
tttttttttttttttttttttttt: linha 2, coluna 2
tttttttttttttttttttttttt: linha 2, coluna 4
tttttttttttttttttttttttt: linha 2, coluna 9
tttttttttttttttttttttttt: linha 2, coluna 17
tttttttttttttttttttttttt: linha 3, coluna 3
tttttttttttttttttttttttt: linha 3, coluna 9
tttttttttttttttttttttttt: linha 3, coluna 15
tttttttttttttttttttttttt: linha 3, coluna 17
tttttttttttttttttttttttt: linha 3, coluna 19
tttttttttttttttttttttttt: linha 3, coluna 20
tttttttttttttttttttttttt: linha 4, coluna 2
tttttttttttttttttttttttt: linha 4, coluna 9
tttttttttttttttttttttttt: linha 4, coluna 14
tttttttttttttttttttttttt: linha 4, coluna 15
tttttttttttttttttttttttt: linha 4, coluna 17
tttttttttttttttttttttttt: linha 5, coluna 3
tttttttttttttttttttttttt: linha 5, coluna 8
tttttttttttttttttttttttt: linha 6, coluna 3
tttttttttttttttttttttttt: linha 6, coluna 4
tttttttttttttttttttttttt: linha 6, coluna 10
tttttttttttttttttttttttt: linha 6, coluna 13
tttttttttttttttttttttttt: linha 6, coluna 14
tttttttttttttttttttttttt: linha 6, coluna 16
tttttttttttttttttttttttt: linha 6, coluna 18
tttttttttttttttttttttttt: linha 7, coluna 3
tttttttttttttttttttttttt: linha 7, coluna 4
tttttttttttttttttttttttt: linha 7, coluna 7
tttttttttttttttttttttttt: linha 7, coluna 9
tttttttttttttttttttttttt: linha 7, coluna 11
tttttttttttttttttttttttt: linha 7, coluna 13
tttttttttttttttttttttttt: linha 7, coluna 17
tttttttttttttttttttttttt: linha 8, coluna 3
tttttttttttttttttttttttt: linha 8, coluna 6
tttttttttttttttttttttttt: linha 8, coluna 8
tttttttttttttttttttttttt: linha 8, coluna 11
tttttttttttttttttttttttt: linha 8, coluna 15
tttttttttttttttttttttttt: linha 8, coluna 18
tttttttttttttttttttttttt: linha 8, coluna 20
tttttttttttttttttttttttt: linha 9, coluna 6
tttttttttttttttttttttttt: linha 9, coluna 9
tttttttttttttttttttttttt: linha 9, coluna 16
tttttttttttttttttttttttt: linha 9, coluna 19
tttttttttttttttttttttttt: linha 10, coluna 3
tttttttttttttttttttttttt: linha 10, coluna 5
tttttttttttttttttttttttt: linha 10, coluna 8
tttttttttttttttttttttttt: linha 10, coluna 10
tttttttttttttttttttttttt: linha 10, coluna 15
tttttttttttttttttttttttt: linha 10, coluna 18
tttttttttttttttttttttttt: linha 11, coluna 3
tttttttttttttttttttttttt: linha 11, coluna 6
tttttttttttttttttttttttt: linha 11, coluna 10
tttttttttttttttttttttttt: linha 11, coluna 13
tttttttttttttttttttttttt: linha 11, coluna 16
tttttttttttttttttttttttt: linha 11, coluna 20
tttttttttttttttttttttttt: linha 12, coluna 1
tttttttttttttttttttttttt: linha 12, coluna 2
tttttttttttttttttttttttt: linha 12, coluna 6
tttttttttttttttttttttttt: linha 12, coluna 9
tttttttttttttttttttttttt: linha 12, coluna 13
tttttttttttttttttttttttt: linha 12, coluna 16
tttttttttttttttttttttttt: linha 12, coluna 19
gggggggggggggggggggggggg: linha 1, coluna 7
gggggggggggggggggggggggg: linha 1, coluna 10
gggggggggggggggggggggggg: linha 1, coluna 13
gggggggggggggggggggggggg: linha 1, coluna 16
gggggggggggggggggggggggg: linha 1, coluna 20
gggggggggggggggggggggggg: linha 2, coluna 8
gggggggggggggggggggggggg: linha 2, coluna 11
gggggggggggggggggggggggg: linha 2, coluna 13
gggggggggggggggggggggggg: linha 2, coluna 15
gggggggggggggggggggggggg: linha 2, coluna 20
gggggggggggggggggggggggg: linha 3, coluna 8
gggggggggggggggggggggggg: linha 3, coluna 11
gggggggggggggggggggggggg: linha 4, coluna 11
gggggggggggggggggggggggg: linha 5, coluna 5
gggggggggggggggggggggggg: linha 5, coluna 11
gggggggggggggggggggggggg: linha 6, coluna 5
gggggggggggggggggggggggg: linha 6, coluna 7
gggggggggggggggggggggggg: linha 7, coluna 6
gggggggggggggggggggggggg: linha 7, coluna 15
gggggggggggggggggggggggg: linha 8, coluna 2
gggggggggggggggggggggggg: linha 8, coluna 4
gggggggggggggggggggggggg: linha 8, coluna 10
gggggggggggggggggggggggg: linha 8, coluna 13
gggggggggggggggggggggggg: linha 8, coluna 16
gggggggggggggggggggggggg: linha 9, coluna 1
gggggggggggggggggggggggg: linha 9, coluna 3
gggggggggggggggggggggggg: linha 9, coluna 5
gggggggggggggggggggggggg: linha 9, coluna 11
gggggggggggggggggggggggg: linha 9, coluna 13
gggggggggggggggggggggggg: linha 9, coluna 17
gggggggggggggggggggggggg: linha 10, coluna 13
gggggggggggggggggggggggg: linha 10, coluna 16
gggggggggggggggggggggggg: linha 11, coluna 7
gggggggggggggggggggggggg: linha 11, coluna 11
gggggggggggggggggggggggg: linha 11, coluna 14
gggggggggggggggggggggggg: linha 11, coluna 17
gggggggggggggggggggggggg: linha 12, coluna 7
gggggggggggggggggggggggg: linha 12, coluna 10
gggggggggggggggggggggggg: linha 12, coluna 14
cccccccccccccccccccccccc: linha 1, coluna 2
cccccccccccccccccccccccc: linha 1, coluna 5
cccccccccccccccccccccccc: linha 1, coluna 6
cccccccccccccccccccccccc: linha 1, coluna 11
cccccccccccccccccccccccc: linha 1, coluna 14
cccccccccccccccccccccccc: linha 1, coluna 19
cccccccccccccccccccccccc: linha 2, coluna 3
cccccccccccccccccccccccc: linha 2, coluna 10
cccccccccccccccccccccccc: linha 2, coluna 12
cccccccccccccccccccccccc: linha 2, coluna 14
cccccccccccccccccccccccc: linha 2, coluna 19
cccccccccccccccccccccccc: linha 3, coluna 4
cccccccccccccccccccccccc: linha 3, coluna 6
cccccccccccccccccccccccc: linha 3, coluna 10
cccccccccccccccccccccccc: linha 3, coluna 13
cccccccccccccccccccccccc: linha 3, coluna 18
cccccccccccccccccccccccc: linha 4, coluna 3
cccccccccccccccccccccccc: linha 4, coluna 4
cccccccccccccccccccccccc: linha 4, coluna 6
cccccccccccccccccccccccc: linha 4, coluna 7
cccccccccccccccccccccccc: linha 4, coluna 10
cccccccccccccccccccccccc: linha 4, coluna 12
cccccccccccccccccccccccc: linha 4, coluna 20
cccccccccccccccccccccccc: linha 5, coluna 1
cccccccccccccccccccccccc: linha 5, coluna 4
cccccccccccccccccccccccc: linha 5, coluna 10
cccccccccccccccccccccccc: linha 5, coluna 12
cccccccccccccccccccccccc: linha 5, coluna 14
cccccccccccccccccccccccc: linha 5, coluna 16
cccccccccccccccccccccccc: linha 5, coluna 18
cccccccccccccccccccccccc: linha 5, coluna 19
cccccccccccccccccccccccc: linha 5, coluna 20
cccccccccccccccccccccccc: linha 6, coluna 1
cccccccccccccccccccccccc: linha 6, coluna 2
cccccccccccccccccccccccc: linha 6, coluna 11
cccccccccccccccccccccccc: linha 6, coluna 15
cccccccccccccccccccccccc: linha 6, coluna 17
cccccccccccccccccccccccc: linha 6, coluna 19
cccccccccccccccccccccccc: linha 7, coluna 1
cccccccccccccccccccccccc: linha 7, coluna 14
cccccccccccccccccccccccc: linha 7, coluna 19
cccccccccccccccccccccccc: linha 8, coluna 1
cccccccccccccccccccccccc: linha 8, coluna 5
cccccccccccccccccccccccc: linha 8, coluna 12
cccccccccccccccccccccccc: linha 8, coluna 17
cccccccccccccccccccccccc: linha 8, coluna 19
cccccccccccccccccccccccc: linha 9, coluna 2
cccccccccccccccccccccccc: linha 9, coluna 4
cccccccccccccccccccccccc: linha 9, coluna 10
cccccccccccccccccccccccc: linha 9, coluna 12
cccccccccccccccccccccccc: linha 9, coluna 14
cccccccccccccccccccccccc: linha 9, coluna 18
cccccccccccccccccccccccc: linha 10, coluna 1
cccccccccccccccccccccccc: linha 10, coluna 11
cccccccccccccccccccccccc: linha 10, coluna 14
cccccccccccccccccccccccc: linha 10, coluna 20
cccccccccccccccccccccccc: linha 11, coluna 1
cccccccccccccccccccccccc: linha 11, coluna 4
cccccccccccccccccccccccc: linha 11, coluna 9
cccccccccccccccccccccccc: linha 11, coluna 15
cccccccccccccccccccccccc: linha 11, coluna 19
cccccccccccccccccccccccc: linha 12, coluna 4
cccccccccccccccccccccccc: linha 12, coluna 8
cccccccccccccccccccccccc: linha 12, coluna 17
cccccccccccccccccccccccc: linha 12, coluna 18
------ FIM ------

