acaca: linha 1, coluna 2
acaca: linha 1, coluna 6
acaca: linha 1, coluna 11
acaca: linha 1, coluna 13
acaca: linha 2, coluna 1
acaca: linha 2, coluna 3
acaca: linha 2, coluna 5
acaca: linha 2, coluna 7
acaca: linha 2, coluna 12
acaca: linha 2, coluna 15
acaca: linha 3, coluna 4
acaca: linha 3, coluna 8
acaca: linha 3, coluna 12
acaca: linha 4, coluna 1
acaca: linha 4, coluna 5
acaca: linha 4, coluna 7
acaca: linha 4, coluna 9
acaca: linha 4, coluna 11
acaca: linha 4, coluna 15
acaca: linha 5, coluna 6
acaca: linha 5, coluna 12
acaca: linha 6, coluna 2
acaca: linha 6, coluna 8
acaca: linha 6, coluna 13
acaca: linha 7, coluna 7
acaca: linha 7, coluna 9
acaca: linha 7, coluna 14
acaca: linha 8, coluna 1
acaca: linha 8, coluna 4
acaca: linha 8, coluna 8
acaca: linha 8, coluna 11
acaca: linha 9, coluna 7
acaca: linha 9, coluna 11
acaca: linha 10, coluna 5
acaca: linha 10, coluna 7
acaca: linha 10, coluna 12
acgt: linha 1, coluna 2
acgt: linha 1, coluna 6
acgt: linha 1, coluna 11
acgt: linha 2, coluna 1
acgt: linha 2, coluna 3
acgt: linha 2, coluna 5
acgt: linha 2, coluna 7
acgt: linha 2, coluna 12
acgt: linha 2, coluna 15
acgt: linha 3, coluna 4
acgt: linha 3, coluna 8
acgt: linha 3, coluna 12
acgt: linha 4, coluna 1
acgt: linha 4, coluna 5
acgt: linha 4, coluna 7
acgt: linha 4, coluna 9
acgt: linha 4, coluna 11
acgt: linha 4, coluna 15
acgt: linha 5, coluna 6
acgt: linha 5, coluna 12
acgt: linha 6, coluna 2
acgt: linha 6, coluna 8
acgt: linha 6, coluna 13
acgt: linha 7, coluna 7
acgt: linha 7, coluna 9
acgt: linha 7, coluna 14
acgt: linha 8, coluna 1
acgt: linha 8, coluna 4
acgt: linha 8, coluna 8
acgt: linha 8, coluna 11
acgt: linha 9, coluna 7
acgt: linha 9, coluna 11
acgt: linha 10, coluna 5
acgt: linha 10, coluna 7
acgt: linha 10, coluna 12
agct: linha 1, coluna 6
agct: linha 1, coluna 11
agct: linha 2, coluna 1
agct: linha 2, coluna 3
agct: linha 2, coluna 5
agct: linha 2, coluna 7
agct: linha 2, coluna 12
agct: linha 2, coluna 15
agct: linha 3, coluna 4
agct: linha 3, coluna 12
agct: linha 4, coluna 1
agct: linha 4, coluna 5
agct: linha 4, coluna 7
agct: linha 4, coluna 11
agct: linha 4, coluna 15
agct: linha 5, coluna 6
agct: linha 5, coluna 12
agct: linha 6, coluna 2
agct: linha 6, coluna 8
agct: linha 6, coluna 13
agct: linha 7, coluna 9
agct: linha 7, coluna 14
agct: linha 8, coluna 1
agct: linha 8, coluna 4
agct: linha 8, coluna 6
agct: linha 8, coluna 11
agct: linha 9, coluna 7
agct: linha 9, coluna 11
agct: linha 10, coluna 5
agct: linha 10, coluna 7
agct: linha 10, coluna 12
atcgc: linha 1, coluna 2
atcgc: linha 1, coluna 13
atcgc: linha 2, coluna 1
atcgc: linha 2, coluna 3
atcgc: linha 2, coluna 5
atcgc: linha 2, coluna 7
atcgc: linha 2, coluna 12
atcgc: linha 2, coluna 15
atcgc: linha 3, coluna 4
atcgc: linha 3, coluna 8
atcgc: linha 3, coluna 12
atcgc: linha 4, coluna 1
atcgc: linha 4, coluna 5
atcgc: linha 4, coluna 7
atcgc: linha 4, coluna 9
atcgc: linha 4, coluna 11
atcgc: linha 5, coluna 6
atcgc: linha 5, coluna 12
atcgc: linha 6, coluna 2
atcgc: linha 6, coluna 8
atcgc: linha 6, coluna 13
atcgc: linha 7, coluna 7
atcgc: linha 7, coluna 9
atcgc: linha 7, coluna 14
atcgc: linha 8, coluna 1
atcgc: linha 8, coluna 4
atcgc: linha 8, coluna 6
atcgc: linha 8, coluna 8
atcgc: linha 8, coluna 11
atcgc: linha 9, coluna 7
atcgc: linha 9, coluna 11
atcgc: linha 10, coluna 5
atcgc: linha 10, coluna 12
cata: linha 1, coluna 4
cata: linha 1, coluna 12
cata: linha 1, coluna 15
cata: linha 2, coluna 2
cata: linha 2, coluna 4
cata: linha 2, coluna 6
cata: linha 2, coluna 9
cata: linha 2, coluna 11
cata: linha 3, coluna 3
cata: linha 3, coluna 7
cata: linha 3, coluna 9
cata: linha 3, coluna 14
cata: linha 4, coluna 13
cata: linha 5, coluna 2
cata: linha 5, coluna 4
cata: linha 5, coluna 8
cata: linha 5, coluna 10
cata: linha 5, coluna 14
cata: linha 6, coluna 1
cata: linha 6, coluna 5
cata: linha 6, coluna 6
cata: linha 6, coluna 11
cata: linha 7, coluna 1
cata: linha 7, coluna 3
cata: linha 7, coluna 12
cata: linha 8, coluna 10
cata: linha 8, coluna 13
cata: linha 9, coluna 2
cata: linha 9, coluna 4
cata: linha 9, coluna 8
cata: linha 10, coluna 13
catgct: linha 1, coluna 4
catgct: linha 1, coluna 12
catgct: linha 1, coluna 15
catgct: linha 2, coluna 2
catgct: linha 2, coluna 4
catgct: linha 2, coluna 6
catgct: linha 2, coluna 9
catgct: linha 2, coluna 11
catgct: linha 3, coluna 3
catgct: linha 3, coluna 7
catgct: linha 3, coluna 9
catgct: linha 3, coluna 14
catgct: linha 4, coluna 13
catgct: linha 5, coluna 2
catgct: linha 5, coluna 4
catgct: linha 5, coluna 8
catgct: linha 5, coluna 10
catgct: linha 5, coluna 14
catgct: linha 6, coluna 1
catgct: linha 6, coluna 5
catgct: linha 6, coluna 6
catgct: linha 6, coluna 11
catgct: linha 7, coluna 1
catgct: linha 7, coluna 3
catgct: linha 7, coluna 12
catgct: linha 8, coluna 10
catgct: linha 8, coluna 13
catgct: linha 9, coluna 2
catgct: linha 9, coluna 4
catgct: linha 9, coluna 8
catgct: linha 10, coluna 13
cgatcgat: linha 1, coluna 4
cgatcgat: linha 2, coluna 2
cgatcgat: linha 2, coluna 4
cgatcgat: linha 2, coluna 6
cgatcgat: linha 2, coluna 11
cgatcgat: linha 3, coluna 3
cgatcgat: linha 3, coluna 7
cgatcgat: linha 3, coluna 14
cgatcgat: linha 4, coluna 13
cgatcgat: linha 5, coluna 2
cgatcgat: linha 5, coluna 4
cgatcgat: linha 5, coluna 8
cgatcgat: linha 5, coluna 10
cgatcgat: linha 5, coluna 14
cgatcgat: linha 5, coluna 15
cgatcgat: linha 6, coluna 1
cgatcgat: linha 6, coluna 5
cgatcgat: linha 6, coluna 6
cgatcgat: linha 6, coluna 11
cgatcgat: linha 7, coluna 1
cgatcgat: linha 7, coluna 3
cgatcgat: linha 7, coluna 12
cgatcgat: linha 8, coluna 10
cgatcgat: linha 8, coluna 13
cgatcgat: linha 9, coluna 2
cgatcgat: linha 9, coluna 4
cgatcgat: linha 9, coluna 8
cgatcgat: linha 9, coluna 14
cgatcgat: linha 10, coluna 9
cgatcgat: linha 10, coluna 13
cgatgcat: linha 1, coluna 4
cgatgcat: linha 2, coluna 2
cgatgcat: linha 2, coluna 4
cgatgcat: linha 2, coluna 6
cgatgcat: linha 2, coluna 11
cgatgcat: linha 3, coluna 3
cgatgcat: linha 3, coluna 7
cgatgcat: linha 3, coluna 14
cgatgcat: linha 4, coluna 13
cgatgcat: linha 5, coluna 2
cgatgcat: linha 5, coluna 4
cgatgcat: linha 5, coluna 8
cgatgcat: linha 5, coluna 10
cgatgcat: linha 5, coluna 14
cgatgcat: linha 5, coluna 15
cgatgcat: linha 6, coluna 1
cgatgcat: linha 6, coluna 5
cgatgcat: linha 6, coluna 6
cgatgcat: linha 6, coluna 11
cgatgcat: linha 7, coluna 1
cgatgcat: linha 7, coluna 3
cgatgcat: linha 7, coluna 12
cgatgcat: linha 8, coluna 10
cgatgcat: linha 8, coluna 13
cgatgcat: linha 9, coluna 2
cgatgcat: linha 9, coluna 4
cgatgcat: linha 9, coluna 8
cgatgcat: linha 9, coluna 14
cgatgcat: linha 10, coluna 9
cgatgcat: linha 10, coluna 13
ctagct: linha 1, coluna 4
ctagct: linha 1, coluna 9
ctagct: linha 1, coluna 12
ctagct: linha 1, coluna 15
ctagct: linha 2, coluna 2
ctagct: linha 2, coluna 4
ctagct: linha 2, coluna 6
ctagct: linha 2, coluna 9
ctagct: linha 2, coluna 11
ctagct: linha 3, coluna 3
ctagct: linha 3, coluna 7
ctagct: linha 3, coluna 9
ctagct: linha 3, coluna 14
ctagct: linha 4, coluna 13
ctagct: linha 5, coluna 2
ctagct: linha 5, coluna 4
ctagct: linha 5, coluna 8
ctagct: linha 5, coluna 10
ctagct: linha 5, coluna 14
ctagct: linha 5, coluna 15
ctagct: linha 6, coluna 5
ctagct: linha 6, coluna 6
ctagct: linha 6, coluna 11
ctagct: linha 7, coluna 1
ctagct: linha 7, coluna 3
ctagct: linha 7, coluna 12
ctagct: linha 8, coluna 10
ctagct: linha 8, coluna 13
ctagct: linha 9, coluna 2
ctagct: linha 9, coluna 4
ctagct: linha 9, coluna 8
ctagct: linha 9, coluna 14
ctagct: linha 10, coluna 3
ctagct: linha 10, coluna 9
ctagct: linha 10, coluna 13
gtagtcg: linha 1, coluna 7
gtagtcg: linha 2, coluna 10
gtagtcg: linha 3, coluna 2
gtagtcg: linha 3, coluna 6
gtagtcg: linha 3, coluna 11
gtagtcg: linha 3, coluna 15
gtagtcg: linha 4, coluna 3
gtagtcg: linha 4, coluna 14
gtagtcg: linha 5, coluna 1
gtagtcg: linha 5, coluna 3
gtagtcg: linha 5, coluna 5
gtagtcg: linha 5, coluna 7
gtagtcg: linha 5, coluna 13
gtagtcg: linha 6, coluna 4
gtagtcg: linha 6, coluna 9
gtagtcg: linha 6, coluna 12
gtagtcg: linha 6, coluna 15
gtagtcg: linha 7, coluna 2
gtagtcg: linha 7, coluna 4
gtagtcg: linha 7, coluna 13
gtagtcg: linha 7, coluna 15
gtagtcg: linha 8, coluna 3
gtagtcg: linha 8, coluna 12
gtagtcg: linha 8, coluna 15
gtagtcg: linha 9, coluna 5
gtagtcg: linha 9, coluna 6
gtagtcg: linha 9, coluna 10
gtagtcg: linha 9, coluna 13
gtagtcg: linha 10, coluna 2
gtagtcg: linha 10, coluna 11
------ FIM ------

